import streamlit as st
import Plan 
st.set_page_config(page_title="My App")
st.header("Diet Plan")
# st.balloons()
Name = st.text_input("Enter your name :")
age = st.text_input("Enter your age ")
height = st.text_input("Enter your height (Feet)")
weight = st.number_input("Enter your weight(kg)")
bp = st.number_input("Enter your Bp")
sugar = st.number_input("Enter your sugar level")
st.text("What is your purpose?")
pur = st.text_area("Purpose",)
str = st.button(label='Submit', key="submit")
result = Plan.plan(age=age,height=height,weight=weight,purpose=pur,sugar=sugar,bp=bp)
st.write(result)
